package io.github.viet_anh_it.book_selling_website.enums;

public enum PermissionEnum {
    ASSIGN_PERMISSION_TO_ROLE,
    ASSIGN_ROLE_TO_ACCOUNT,
    LOCK_ACCOUNT,
    UNLOCK_ACCOUNT,
    APPROVE_REVIEW,
    DELETE_REVIEW,
    CREATE_BOOK,
    UPDATE_BOOK,
    DELETE_BOOK,
    CREATE_CATEGORY,
    GET_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,
    UPDATE_ORDER_STATUS,
    POST_REVIEW,
    ADD_TO_CART,
    DELETE_CART_ITEM,
    CREATE_ORDER,
    CANCEL_ORDER,
}
